### ISSUE TITLE
Searching not working

### ISSUE THREAD

**Issue by delphir-com** [weirdgiraffe/plugin.video.giraffe.seasonvar#1]
> 21:59:50 T:140692290516736   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode characters in position 7-10: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/k/.kodi/addons/plugin.video.giraffe.seasonvar-0.0.1/run_plugin_video.py", line 16, in <module>
                                                main()
                                              File "/home/k/.kodi/addons/plugin.video.giraffe.seasonvar-0.0.1/resources/site-packages/addon/plugin_video.py", line 210, in main
                                                }[action](addon.args)
                                              File "/home/k/.kodi/addons/plugin.video.giraffe.seasonvar-0.0.1/resources/site-packages/addon/plugin_video.py", line 185, in screen_search
                                                'url': item['url']}),
                                              File "/home/k/.kodi/addons/plugin.video.giraffe.seasonvar-0.0.1/resources/site-packages/addon/common.py", line 61, in make_url
                                                return '{0}?{1}'.format(addon_url, urlencode(params))
                                              File "/usr/lib/python2.7/urllib.py", line 1343, in urlencode
                                                v = quote_plus(str(v))
                                            UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-10: ordinal not in range(128)
                                            -->End of Python script error report<--
21:59:50 T:140693972035904   ERROR: GetDirectory - Error getting plugin://plugin.video.giraffe.seasonvar/?action=screen_search
21:59:50 T:140693972035904   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.giraffe.seasonvar/?action=screen_search) faile

**Comment by weirdgiraffe** [comment]
поставлю сегодня-завтра

**Comment by weirdgiraffe** [comment]
fixed in release 0.0.3
