### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by YegresOm** [weirdgiraffe/plugin.video.giraffe.seasonvar#4]
System: OpenELEC/Kodi/Raspberry PI

00:01:36 440734.281250 T:1684898880  NOTICE: -->Python Interpreter Initialized<--
00:01:37 440735.281250 T:1684898880  NOTICE: {'action': 'screen_search'}
00:01:41 440738.812500 T:1684898880   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: __init__() takes at most 3 arguments (4 given)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.giraffe.seasonvar/run_plugin_video.py", line 16, in <module>
                                                main()
                                              File "/storage/.kodi/addons/plugin.video.giraffe.seasonvar/resources/site-packages/addon/plugin_video.py", line 205, in main
                                                }[action](addon.args)
                                              File "/storage/.kodi/addons/plugin.video.giraffe.seasonvar/resources/site-packages/addon/plugin_video.py", line 181, in screen_search
                                                s = Show(item['url'], None, None)
                                            TypeError: __init__() takes at most 3 arguments (4 given)
                                            -->End of Python script error report<--

**Comment by weirdgiraffe** [comment]
check version 0.1.2

**Comment by YegresOm** [comment]
Works. Great!
Thanks for quick reaction!
